#
# CircleCI Builder for ATD's MDS ETL Container
#

version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: "Run Unit Tests"
          command: |
            apt-get install libspatialindex-dev
            pip install -r requirements.txt
            pytest -v
      - run:
          name: "Building Docker Container"
          command: |
            source .circleci/docker-helper.sh
            build_container
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - deploy